sudo: required
dist: trusty
language: go
go:
  - "1.10.x"

cache:
  directories:
    - $HOME/.ccache

os:
  - osx
  - linux

before_install:
  - go get github.com/opencontainers/runtime-spec/specs-go
  - go get github.com/urfave/cli
  - go get github.com/sirupsen/logrus


script: make
