language: go
go:
  - "1.10.x"

cache:
  directories:
    - $HOME/.ccache

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      before_install:
        - sudo apt-get install jq
    - os: osx
      before_install:
        - mkdir -p ~/.local/bin
        - HOMEBREW_NO_AUTO_UPDATE=1 brew install jq
        - export PATH=/usr/local/opt/ccache/libexec:$HOME/.local/bin:$PATH
        - ln -sf /usr/local/bin/gsha256sum ~/.local/bin/sha256sum

script:
  - go get github.com/opencontainers/runtime-spec/specs-go
  - go get github.com/urfave/cli
  - go get github.com/sirupsen/logrus
  - go get github.com/opencontainers/runc/libcontainer/specconv
  - make
  - sudo make install
  - bash -ex test/standalone-test.sh

