language: go
go:
  - "1.10.x"

cache:
  directories:
    - $HOME/.ccache

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      before_install:
        - sudo apt-get install jq
    - os: osx
      before_install:
        - brew install jq

script: 
  - go get github.com/opencontainers/runtime-spec/specs-go
  - go get github.com/urfave/cli
  - go get github.com/sirupsen/logrus
  - go get github.com/opencontainers/runc/libcontainer/specconv
  - make
  - bash test/standalone-test.sh

